modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="shineals_end_update"
version="1.0"
displayName="ShiNeaL's Endgrowth"
displayURL="https://www.shineal.org/"
credits="ShinyDragon96, TgwCreeper, GlitchedMastery"
authors="ShineaL"
description="An end MOD, which adds mysterious creatures, blocks and items to the game"

[[dependencies.shineals_end_update]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.shineals_end_update]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

