modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="shineals_endergrowth"
version="1.0"
displayName="ShiNeaL's Endergrowth"
displayURL="https://shineal.org"
credits="Created by ShinyDragon96, TgwCreeper, & GlitchedMastert"
authors="ShineaL Studios"
description="An End Overhaul MOD By ShineaL Studios"

[[dependencies.shineals_endergrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.shineals_endergrowth]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

